services:
  - type: web
    name: fpms-backend
    env: java
    buildCommand: mvn clean package -Pprod -DskipTests
    startCommand: java -jar target/fpms-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1